name: build
on: [push]
jobs:
  build:
    runs-on: windows-2025
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: msbuild setup
        uses: microsoft/setup-msbuild@v1.1

      - name: generate versions
        run: |
          pushd tools
          node version-setup.js
          popd

      - name: run msbuild
        shell: cmd
        run: |
          MSBuild.exe aosora-shiori.sln -property:Configuration=Release;Platform="x86" -t:rebuild

      - name: run vsce package
        run: |
          pushd vscode-extension
          npm install
          npm install vsce
          npx vsce package -o vscode-extension.vsix
          popd

      - name: upload build
        uses: actions/upload-artifact@v4
        with:
          name: aosora-shiori
          path: Win32\Release

      - name: upload vscode-extension
        uses: actions/upload-artifact@v4
        with:
          name: vscode-extension.vsix
          path: vscode-extension\vscode-extension.vsix

      - name: upload demo-nar
        uses: actions/upload-artifact@v4
        with:
          name: demo.nar
          path: ssp\ghost\test
      

