name: build
on: [push]
jobs:
  build:
    runs-on: windows-2025
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: msbuild setup
        uses: microsoft/setup-msbuild@v1.1

      - name: generate versions
        run: |
          pushd tools
          node version-setup.js
          popd

      - name: run msbuild
        shell: cmd
        run: |
          MSBuild.exe aosora-shiori.sln -property:Configuration=Deploy;Platform="x86" -t:rebuild

      - name: run vsce package
        run: |
          pushd vscode-extension
          npm install
          npm install vsce
          npx vsce package -o vscode-extension.vsix
          popd

      - name: make demo.nar
        uses: thedoctor0/zip-release@0.7.5
        with:
          type: zip
          filename: demo.zip
          directory: ssp\ghost\test

      - name: collect files
        shell: cmd
        run: |
          mkdir temp-github
          copy /Y vscode-extension\vscode-extension.vsix temp-github\vscode-extension.vsix
          copy /Y ssp\ghost\test\demo.zip temp-github\demo.nar
          copy /Y Win32\Deploy\aosora.dll temp-github\aosora.dll
          copy /Y Win32\Deploy\aosora.pdb temp-github\aosora.pdb

      - name: upload
        uses: actions/upload-artifact@v4
        with:
          name: aosora-shiori
          path: temp-github


